[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.12.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
