const data = {
  text: `i make products for the web, from concept to production, translating ideas into pixel-perfect interfaces backed by performant systems. recent years spent with startups and agencies designing experiences, architecting and shipping full-stack applications that scale. focused on modern web technologies with emphasis on typescript, react and next js. core stack:`,

  stack: [
    'JavaScript (ES6+)',
    'TypeScript',
    'React 19',
    'Next.js 15',
    'Gatsby',
    'Astro',
    'Solid.js',
    'SolidStart',
    'Node.js',
    'NestJS',
    'Express.js',
    'Fastify',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Drizzle ORM',
    'Prisma',
    'GraphQL',
    'tRPC',
    'REST API',
    'Swagger',
    'JWT',
    'Passport',
    'WebSocket',
    'Socket.io',
    'Tailwind CSS',
    'Styled Components',
    'Emotion',
    'Material-UI',
    'Radix UI',
    'shadcn/ui',
    'PrimeNG',
    'Contentful CMS',
    'Payload CMS',
    'WordPress',
    'Zustand',
    'Redux',
    'React Router',
    'React Query',
    'Vite',
    'Capacitor',
    'Android TV',
    'WebOS',
    'Tizen',
    'AWS S3',
    'Stripe',
    'Docker',
    'GitHub Actions',
    'Nginx',
    'Playwright',
    'Jest',
    'Vitest',
    'React Leaflet',
    'OpenAI API',
  ],
};

export default data;
