const data = {
  text: `i make things for the web from concept to production, translate ideas into pixel-perfect interfaces backed by performant systems. five years with startups and agencies, shipping from AI-powered content platforms to connected TV applications. focused on modern web technologies with emphasis on typescript, react and next js. core stack:`,

  stack: [
    'TypeScript',
    'JavaScript (ES6+)',
    'React',
    'Next.js',
    'Astro',
    'Solid.js',
    'SolidStart',
    'Gatsby',
    'NestJS',
    'Express.js',
    'Fastify',
    'Node.js',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Drizzle ORM',
    'Prisma',
    'GraphQL',
    'tRPC',
    'REST API',
    'Tailwind CSS',
    'Styled Components',
    'Emotion',
    'Material-UI',
    'Radix UI',
    'shadcn/ui',
    'Payload CMS',
    'Zustand',
    'Redux',
    'React Router',
    'TanStack Query',
    'Capacitor',
    'Android TV',
    'WebOS',
    'Tizen',
    'AWS S3',
    'Docker',
    'GitHub Actions',
    'Playwright',
    'Jest',
    'Vitest',
    'OpenAI API',
    '...',
  ],
};

export default data;
